version: '2.0'

networks:
  backend:

services:

  app:
    build: .
    working_dir: /opt/user-manager
    ports:
      - '80:80'
    volumes:
      - .:/opt/user-manager
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:5.7.25
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: user_manager
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - backend
